### ISSUE TITLE
Google Closure unavailable. TypeError: goog.isBoolean is not a function

### ISSUE THREAD

**Issue by rlhk** [thheller/shadow-cljs#877]
Got a mysterious error on a shadow-cljs react-native project
In "watch" mode the error shows like the screen capture.
However the app is all good if the output index.js is compiled in "release" mode.
The error first appeared when I upgrade shadow-cljs from 2.11.8 to 2.12.5. I managed to make it disappear by cleaning everything. Including removing the old globally installed shadow-cljs, start from fresh shell etc...
Then I tried to upgrade DataScript from 1.0.0 to 1.1.0. This time, no matter how I reset, the same error persists. Note that "release" mode is all good.

Any clue?

![Simulator Screen Shot - iPhone 8 - 2021-04-26 at 23 07 27](https://user-images.githubusercontent.com/17818753/116105806-411b6200-a6e4-11eb-9820-212fc7f61054.png)

**Comment by thheller** [comment]
`shadow-cljs` `2.12.x` requires the recently released CLJS 1.10.844 and the matching Closure Compiler/Library versions. Unfortunately there have been some breaking changes in the Closure Library (eg. removal of `goog.isBoolean`)

See https://clojurescript.org/news/2021-04-06-release#_noteworthy_breaking_changes

**Comment by rlhk** [comment]
I updated cljs in my global deps and still see the error. Does that mean the error was caused by some libs using the removed google closure fns?

**Comment by thheller** [comment]
Yes, anything using those functions will break. You can downgrade the closure-compiler/closure-library versions if you must but I expect common libraries to be updated soon since everyone will be affected by this when upgrading CLJS.
