### ISSUE TITLE
Build errors when migrating from 2.8.93 to 2.10.17

### ISSUE THREAD

**Issue by luishdosreis** [thheller/shadow-cljs#765]
Trying to upgrade from `2.8.93` to `2.10.17`. When watching the main app module locally I'm getting the following build errors:
```
Closure compilation failed with 2 errors
--- node_modules/@firebase/util/dist/index.cjs.js:31
@define must be initalized on a static qualified name in global or module scope
--- node_modules/@firebase/util/dist/index.cjs.js:35
@define must be initalized on a static qualified name in global or module scope
```
Seems like it's a GCP related error for the firebase module. The aforementioned lines in the module's file look like this
```
    /**
     * @define {boolean} Whether this is the client Node.js SDK.
     */
    NODE_CLIENT: false,
    /**
     * @define {boolean} Whether this is the Admin Node.js SDK.
     */
    NODE_ADMIN: false,
```
