### ISSUE TITLE
Various issues with 2.12.0

### ISSUE THREAD

**Issue by kanwei** [thheller/shadow-cljs#862]
This is with clojurescript 1.10.773

```
Note: The following stack trace applies to the reader or compiler, your code was not executed.
CompilerException Syntax error compiling at (shadow/cljs/devtools/server/nrepl.clj:1:1). #:clojure.error{:phase :compile-syntax-check, :line 1, :column 1, :source "shadow/cljs/devtools/server/nrepl.clj"}
	clojure.core/throw-if (core.clj:5856)
	clojure.core/load-lib (core.clj:5942)
	clojure.core/load-lib (core.clj:5917)
	clojure.core/apply (core.clj:669)
	clojure.core/load-libs (core.clj:5974)
	clojure.core/load-libs (core.clj:5958)
	clojure.core/apply (core.clj:669)
	clojure.core/require (core.clj:5996)
	clojure.core/require (core.clj:5996)
	shadow.cljs.devtools.server.nrepl/eval62742/loading--6737--auto----62743 (nrepl.clj:1)
	shadow.cljs.devtools.server.nrepl/eval62742 (nrepl.clj:1)
	shadow.cljs.devtools.server.nrepl/eval62742 (nrepl.clj:1)
Caused by:
Exception namespace 'cider.piggieback' not found
shadow-cljs - server version: 2.12.0 running at http://localhost:9630
[:mp360] Configuring build.
[:mp360] Compiling ...
[:mp360] Build failure:
Closure compilation failed with 15 errors
--- node_modules/react-day-picker/build/DateUtils.js:27
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:38
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:49
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:63
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:78
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:93
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:107
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:121
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:135
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:151
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:166
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:200
@export is not supported on this expression.
--- node_modules/react-day-picker/build/DateUtils.js:215
@export is not supported on this expression.
--- node_modules/react-day-picker/build/ModifiersUtils.js:22
@export is not supported on this expression.
--- node_modules/react-day-picker/build/ModifiersUtils.js:70
@export is not supported on this expression.

[:mp360partners] Configuring build.
[:mp360partners] Compiling ...
[2021-03-31 21:19:37.580 - WARNING] :shadow.cljs.devtools.server.util/handle-ex - {:msg {:type :start-autobuild}}
NoClassDefFoundError Could not initialize class cljs.repl__init
	java.lang.Class.forName0 (Class.java:-2)
	java.lang.Class.forName (Class.java:468)
	clojure.lang.RT.classForName (RT.java:2212)
	clojure.lang.RT.classForName (RT.java:2221)
	clojure.lang.RT.loadClassForName (RT.java:2240)
	clojure.lang.RT.load (RT.java:449)
	clojure.lang.RT.load (RT.java:424)
	clojure.core/load/fn--6856 (core.clj:6115)
	clojure.core/load (core.clj:6114)
	clojure.core/load (core.clj:6098)
	clojure.core/load-one (core.clj:5897)
	clojure.core/load-one (core.clj:5892)
```

**Comment by thheller** [comment]
`2.12.0` bumped the clojurescript version to the new `1.10.844` (announcement upcoming). It also bumped to newer closure-compiler and closure-library versions and will no longer work with CLJS 1.10.773.

**Comment by thheller** [comment]
The `@export` issue should be fixed in `2.12.1`.

**Comment by kanwei** [comment]
Thanks! No errors as of 2.12.1
