### ISSUE TITLE
shadow-cljs 2.16.0: is output-feature-set ignored?

### ISSUE THREAD

**Issue by DavidVujic** [thheller/shadow-cljs#956]
I'm experiencing issues with the compiled JavaScript, when bumping the `shadow-cljs` version from 2.15.8 to 2.16.0.

In my repo, I'm using `mui5` (not sure if that is relevant here) and `Storybook`. To make the Storybook things work smoothly, I have `:output-feature-set :es5` in the `:compiler-options` section. With this, Storybook doesn't have to use Babel when compiling the output from shadow-cljs.

When bumping shadow-cljs to 2.16.0 it looks like that the output-feature-set setting is causing issues. The web site will generate errors:
```
main.js:1470 TypeError: $jscomp.inherits is not a function
    at eval (es6.js:144)
    at Object.goog.loadModule (main.js:304)
    at eval (es6.js:11)
    at eval (<anonymous>)
    at Object.goog.globalEval (main.js:503)
    at Object.env.evalLoad (main.js:1578)
    at main.js:1656
reportError @ main.js:1470
env.evalLoad @ main.js:1580
(anonymous) @ main.js:1656
main.js:1472 The above error occurred when loading "goog.iter.es6.js". Any additional errors after that one may be the result of that failure. In general your code cannot be trusted to execute properly after such a failure. Make sure to fix the first one before looking at others.
```
All is good in the current alias, when removing `:output-feature-set :es5`.

But when running Storybook, I run into other issues, that I think is related to ES5/ES6:
```
index.js:49 Unexpected error while loading ./app.stories.button_stories.js: TypeError: Cannot destructure property 'USE_CLIENT_HINTS' of 'goog.require(...)' as it is null.
```

So, what I would like is to be able to set the `:output-feature-set :es5`. I'm not sure what goes wrong here, if it is the ClojureScript version or shadow-cljs. Let me know if you need more information.

**Comment by DavidVujic** [comment]
Might be related to https://github.com/thheller/shadow-cljs/issues/935

**Comment by DavidVujic** [comment]
This is the repo I'm working on (currently using shadow-cljs 2.15.8): https://github.com/DavidVujic/clojurescript-amplified/blob/main/shadow-cljs.edn

**Comment by thheller** [comment]
> With this, Storybook doesn't have to use Babel when compiling the output from shadow-cljs.

Can you expand on this a little bit? I'm pretty sure Storybook itself uses "modern" JS so I don't quite understand why shadow-cljs has to polyfill anything? Also why polyfill at all? I'm assuming you are using a modern browser to use storybook?

`:output-feature-set` is definitely still there but the way it is handled might have changed in the Closure Compiler so I'm unsure where to pinpoint anything. I can't try your repro since I'm not going to install AWS Amplify. Would help to have a repro that doesn't all that other setup.

Going from 2.15.8 to 2.16.0 involves a big closure compiler+library upgrade so I'd suspect the issue lies within there somewhere but can't say much more.

**Comment by DavidVujic** [comment]
I just realized that I might have misunderstood how Storybook packages code. Currently, I have a "ignore all code" in the Storybook babel config. I will read up more on what happens when Storybook does it's packaging and will try to find out how it should be configured.

**Comment by DavidVujic** [comment]
I haven't gotten any closer to solving this, but here's a storybook-only branch: https://github.com/DavidVujic/clojurescript-amplified/tree/storybook-only

These issues appear in v216.0, but as you wrote, it could be caused by the ClojureScript version.

What I'm doing here is:
compiling the app with target `:browser`
compiling the storybook alias with target `:npm-module`

The compiled storybook code is passed on to the Storybook packaging (using Webpack and Babel). I have disabled babel (in the `.storybook/.babelrc` file), but I don't think there is any difference in the result. These warnings appear (one row for each story) in the browser console (and there aren't any stories).

Maybe the `'USE_CLIENT_HINTS' of 'goog.require(...)'` is a clue, do you have any ideas?


```
index.js:49 Unexpected error while loading ./app.stories.button_stories.js: TypeError: Cannot destructure property 'USE_CLIENT_HINTS' of 'goog.require(...)' as it is null.
warn @ index.js:49
(anonymous) @ loadCsf.js:63
(anonymous) @ loadCsf.js:56
(anonymous) @ loadCsf.js:55
ConfigApi.configure @ config_api.js:19
(anonymous) @ loadCsf.js:223
configure @ index.js:28
./.storybook/generated-stories-entry.js @ generated-stories-entry.js:6
__webpack_require__ @ bootstrap:24
__webpack_exec__ @ util.inspect:1
(anonymous) @ util.inspect:1
__webpack_require__.O @ chunk loaded:23
(anonymous) @ util.inspect:1
webpackJsonpCallback @ jsonp chunk loading:558
(anonymous) @ main.iframe.bundle.js:1
...
```

**Comment by thheller** [comment]
Thanks for the repro. Should be fixed in 2.16.2.

FWIW your storybook config should use this path

```
  "stories": [
    "../public/js/stories/*_stories.js"
  ],
```

Otherwise it'll end up including the `cljs-runtime` dir which it has no use for and may cause other problems. I would even suggest moving it ouf of the public folder entirely since it doesn't need to be there and IMHO shouldn't.

**Comment by DavidVujic** [comment]
That's fantastic, thank you!
